name: dumble
version: 1.3.0
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  protobuf: ^1.0.1
  meta: ^1.1.8
  pointycastle: ^1.0.2
  convert: ^2.1.1
dev_dependencies:
  opus_dart:
    path: ../opus_dart