name: dumble
version: 0.7.2
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
description: A Mumble transport client framework supporting multiple Mumble features such as fully encrypted udp transport or user management.
homepage: https://github.com/EPNW/dumble
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  protobuf: ^1.0.1
  meta: ^1.1.8
  pointycastle: ^1.0.2
  convert: ^2.1.1
  fixnum: ^0.10.11
  
dev_dependencies:
  opus_dart:
    git: https://github.com/EPNW/opus_dart
