name: dumble
version: 0.9.0
description: A Mumble transport client framework supporting multiple Mumble features such as fully encrypted udp transport or user management
repository: https://github.com/EPNW/dumble
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  protobuf: ^3.1.0
  meta: ^1.12.0
  pointycastle: ^3.9.1
  convert: ^3.1.1
  fixnum: ^1.1.0
false_secrets:
 - /example/assets/dumble_cert.pem
 - /example/assets/dumble_key.pem