name: dumble
version: 0.8.1
description: A Mumble transport client framework supporting multiple Mumble features such as fully encrypted udp transport or user management
repository: https://github.com/EPNW/dumble
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  protobuf: ^2.0.0
  meta: ^1.3.0
  pointycastle: ^3.1.2
  convert: ^3.0.0
  fixnum: ^1.0.0
